services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=kuxyl'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '1234:5432'
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.4.7'
    command: 'start-dev'
    environment:
      - 'KC_BOOTSTRAP_ADMIN_USERNAME=admin'
      - 'KC_BOOTSTRAP_ADMIN_PASSWORD=admin'
    ports:
      - '1235:8080'
